### ISSUE TITLE
test-result.txt missing in test folder

### ISSUE THREAD

**Issue by jyluo** [eisop/webserver#10]
When running test.sh, it reports that test-result.txt is missing.
Also, if it is missing, I'm not sure that it should pass.

jeff@cookie:~/workspace/jsr308/webserver/test$ ./test.sh
NullnessExample
diff: test-result.txt: No such file or directory
PASS.
jeff@cookie:~/workspace/jsr308/webserver/test$ ls
run-result.txt  test-input.txt  test.sh

**Comment by CharlesZ-Chen** [comment]
Hi Jeff, do you pull the newest version before running test.sh? This was a bug and I've already fixed it.

**Comment by CharlesZ-Chen** [comment]
I've already add the test-result.txt, and current its name is changed as `expected-result.txt`.
I will test the test.sh again and see why it will still give a PASS even some thing is missing. Thanks for reveal this issue!

**Comment by jyluo** [comment]
Oh I didn't update yet. Let me try.

**Comment by jyluo** [comment]
Yep, it is there and working fine. Sorry!

**Comment by CharlesZ-Chen** [comment]
That's fine! I will enhance test.sh to let it gives a warning if there were missing files.
