### ISSUE TITLE
Provide a "release" version

### ISSUE THREAD

**Issue by wmdietl** [eisop/webserver#12]
At the moment the current Checker Framework is cloned and built for the website. This gives the most up-to-date code, which might contain issues.

It would be nice to have a version of the service that uses the latest release version, available from checkerframework.org, and use that version for the `/live` site. I'm fine with having to manually download the release zip.

The current approach should be kept, but mapped to a `/live-dev` URL.

**Comment by jyluo** [comment]
I think the zip could be auto downloaded and unpacked with some scripting.

For a developer who has an existing copy of CF, it would be nice to not have to re-clone a copy of CF and instead work with the existing copy of CF (through a command line option). This would be useful for local demos of new checkers that have not yet been merged into CF's trunk.

**Comment by CharlesZ-Chen** [comment]
Hi Jeff, 

Currently you can manually change the value of $JSR308 in run-checker.sh to customise the location of CF:
https://github.com/eisop/webserver/blob/master/run-checker.sh#L15

It is a good point to avoid re-clone of CF for developers who have an existing copy of CF. Will have a look on it to see how to enhance it. Thanks

**Comment by jyluo** [comment]
I'll create a separate Issue for this latter feature.

**Comment by CharlesZ-Chen** [comment]
Hi Prof. Dietl, now we can deploy the released version of checker framework by passing the url of `released-checker-framework.zip` to `delopy-checkerweb.sh`.

See `step 2` in `Production Server Deployment` in README.md:
https://github.com/eisop/webserver/blob/master/README.md

But currently we still need to deploy two servers separately:  one serves with released version of cf, and the other one serves with dev-version of cf.

Is that a feasible solution for our current requirement?

**Comment by wmdietl** [comment]
Recent updates fixed this.
http://eisop.uwaterloo.ca/live-dev is now a development build and
http://eisop.uwaterloo.ca/live is a release build.
