### ISSUE TITLE
Allow use of existing version of CF for developers

### ISSUE THREAD

**Issue by jyluo** [eisop/webserver#14]
For a developer who has an existing copy of CF, it would be nice to not have to re-clone a copy of CF and instead work with the existing copy of CF (through a command line option). This would be useful for local demos of new checkers that have not yet been merged into CF's trunk.

The command line option could ask for the path to an existing directory where CF is installed at, then write that out to a short file to be used later on.

Alternatively, the jsr308 folder could be programmed through the script to be a soft link to the CF's parent folder (although not all developers necessarily put the checker framework under a jsr308 folder).

**Comment by wmdietl** [comment]
Isn't it easy enough to make the jsr308 directory a symbolic link to wherever you have your clone of the projects? If you don't have the checker-framework in the same directory as the other projects, you will need to provide a bunch of build options; I don't think we need to spend time on supporting that use case.

**Comment by jyluo** [comment]
In that case, I think the manual for webserver can clarify that a symbolic link to an existing jsr308 folder with all 3 main projects can be set up before executing `deploy-checkerweb.sh`

**Comment by CharlesZ-Chen** [comment]
Sure, I can clarify this in the manual.

**Comment by CharlesZ-Chen** [comment]
Hi Jeff,
I've made a small update on deploy script, and also clarify this situation in the manual. Please let me know if you still have problems on this. Thanks!

**Comment by jyluo** [comment]
Hey Charles,
It works. Thanks!
I'll close this ticket.
