### ISSUE TITLE
String above code becomes out of date

### ISSUE THREAD

**Issue by mernst** [eisop/webserver#16]
Above the code window there is text that is one of these strings:
    Write Java code here:
    Checker passed!
    Please fix the bug(s) and check again!
I think the first one should say
    Write Java code here, then click [check]
where check is a button or link that does the same think as the current check button.
That will make it more obvious what a user should do.

More importantly, as soon as the user makes any edit, I think this text:
  Checker passed!
  Please fix the bug(s) and check again!
should be replaced by
  Write Java code here, then click [check]
because otherwise it's weird to see a window with obviously-broken code that says at the top "Checker passed!".

**Comment by CharlesZ-Chen** [comment]
Thanks for the suggestion. I will update it soon.

**Comment by CharlesZ-Chen** [comment]
Already update it. Now the reminder string would change to "Write Java code here, then click [check]" whenever the user makes some edit.

**Comment by wmdietl** [comment]
Looks good.
