### ISSUE TITLE
Order of type-checkers in list

### ISSUE THREAD

**Issue by mernst** [eisop/webserver#17]
To make it easier to keep the list of type-checkers up to date, I suggest that they should be listed in the examples section of the webpage in the same order they appear in the manual.

Also, please remove the IGJ and Javari type systems.

**Comment by CharlesZ-Chen** [comment]
Sure, will update it.

**Comment by CharlesZ-Chen** [comment]
Now in the develop version, the type-checkers keep the same order as in the manual both in the example section and the selection section. 

Just leave this comment as a note, and I will close this issue when we merge the change to the public version.

Thanks!

**Comment by wmdietl** [comment]
Updated the server.
