### ISSUE TITLE
Table of errors formatting

### ISSUE THREAD

**Issue by mernst** [eisop/webserver#18]
In the table of errors, "NO." should be "No.", with a lowercase letter "o".

In the table of errors, I suggest that you retain the line breaks that the type-checker issues.  For example, instead of

  Error: [assignment.type.incompatible] incompatible types in assignment. found : @Fenum("A") int required: @Fenum("B") int

the webpage would show three lines of output:

  Error: [assignment.type.incompatible] incompatible types in assignment.
  found : @Fenum("A") int
  required: @Fenum("B") int

**Comment by CharlesZ-Chen** [comment]
I didn't add any additional string processing on the error information that the type-checker issues. Maybe some thing is wrong, I will check it. Thanks!

**Comment by CharlesZ-Chen** [comment]
Already add additional string processing to show the line breaks in error table. I will close this issue when the public version merge this change.

Thanks!

**Comment by wmdietl** [comment]
Looks good!
