### ISSUE TITLE
Update required : linear checker removal

### ISSUE THREAD

**Issue by ashishrana160796** [eisop/webserver#35]
As for current version `2.4.0` linear checker is not part of it. Also, as change-log points out `Removed the Linear Checker, whose implementation was inconsistent with its documentation`. This update is required as there is no documentation for it, plus this inconsistency factor.
It is quite ambiguous to have a checker that is not part of current software and with no documentation.

**Comment by CharlesZ-Chen** [comment]
Thanks for reporting this inconsistence! We will update live demo server to keep consistent with the current version of Checker Framework.
