### ISSUE TITLE
Make source input field resizable

### ISSUE THREAD

**Issue by wmdietl** [eisop/webserver#5]
At the moment, the source code input field is of a fixed size.
It would be convenient to allow resizing of the input field.

**Comment by CharlesZ-Chen** [comment]
Now when users move mouse to the bottom of input field, they will be given a hint of input field is resizable. Users can resize the input field by dragging up or down the bottom of the input field.

There still have space to improve this functionality, but I just want to make a workable one and have a demo first.

This version is already updated on 8081 test server.

**Comment by wmdietl** [comment]
Thanks, this already looks quite nice!
I cannot make the input field smaller than the default 22 lines. For small screen resolutions it would be useful to allow even fewer lines.

Would it be possible to change the width also?

**Comment by CharlesZ-Chen** [comment]
Sure, I can make the default height smaller. Change width is also possible,
will update it soon.

2016年4月18日星期一，Werner Dietl <notifications@github.com> 写道：

**Comment by CharlesZ-Chen** [comment]
Hi Prof. Dietl,

Now the width of input field could be re-sized in a range of 50%-120% relative to its parent div. And the min-height of input field is set to around 14 lines. 
Does this size setting works fine in your screen?
