### ISSUE TITLE
Add links to Checker Framework manual

### ISSUE THREAD

**Issue by wmdietl** [eisop/webserver#9]
In the list of type system examples, instead of just listing the type system name, include a link to the corresponding Checker Framework manual section:
Nullness (*manual*): Ex 1 | Ex 2 ...

Maybe that link can also be shown for the selected type system, after the "Choose a type system: Nullness" selector.

What would be really nice, but requires some work and playing with the layout, would be minimal type system summaries shown to the right of the program source input box. A list of the qualifiers, the subtype relationship, and the main type rules. Again, the summary would change depending on the selection.

**Comment by CharlesZ-Chen** [comment]
Add links one seems easy to implement. Also, will try to workout a solution on type system summaries.

**Comment by CharlesZ-Chen** [comment]
Hi Prof. Dietl, 

Currently my idea of adding links of manual is to build the checker manual in `checker-framework/checker/manual` to get the `manual.html`, and then add links to this html in our main page.

However, it seems `eisop` server lack of some prerequisites to build the manual as here indicates:
http://types.cs.washington.edu/checker-framework/current/checker-framework-manual.html#building-prerequisites

It seems we need `hevea`, `librsvg`, and `dia` on the server first.

I've google the instruction of installing these packages on RHEL, but I don't have the sudo right to have a try.

https://pkgs.org/fedora-centos-rhel-opensuse-mandriva/olea/hevea-1.10-1.i386.rpm.html

http://dia-installer.de/download/linux.html.en

https://www.npmjs.com/package/librsvg#ubuntu

Is it possible that to have these packages on our server? Thanks!

**Comment by CharlesZ-Chen** [comment]
Hi Prof. Dietl, it seems the released version of `checker framework` has already built the `manual.html` for us. So there is no need to install these packages anymore. Thanks!

**Comment by wmdietl** [comment]
You could simply link to the current manual at checkerframework.org. Alternatively, using the manual from the last release is also fine.

**Comment by CharlesZ-Chen** [comment]
Now every example section has a link to the current manual at checkerframework.org, the dynamic link shows within the type-checkers selection section would update soon.

**Comment by CharlesZ-Chen** [comment]
Dynamic link has implemented and also fix the small format problem.

**Comment by wmdietl** [comment]
One slight issue:

- start with the initial Nullness Checker; you see the correct manual link
- click on a different example; source code and type system selection update, but manual link doesn't update.

Would it be easy to open the manual links in a new tab?

**Comment by CharlesZ-Chen** [comment]
Ah! Sorry about that,  this is a corner case I forgot to consider about... Will fix it soon.

Yes, it is easy to open the manual links in a new tab, will update it soon.

Thanks,

**Comment by CharlesZ-Chen** [comment]
Hi Prof. Dietl, I've already fix this bug and also let the manual links to be opened in a new tab.

The fix has already tested in our dev-version checker web.

It might need to clear the browser's cache first to see the fix.

Thanks,

**Comment by wmdietl** [comment]
Great! This works very nicely now. I've updated the server.
